pipeline {
    agent any

    tools {
        nodejs "nodeForAuth"
    }

    ///environment {
    ///    SCANNER_HOME = tool "sonarqube"
    ///}

    stages {
        stage('Checkout') {
            steps {
                git branch: 'automatizacion-04', url: 'https://github.com/odiador/retos-microservicios.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pwd'
                echo "==========================================="
                echo "📦 Instalando dependencias de Node.js..."
                echo "==========================================="
                sh 'node --version'
                sh 'npm --version'
                dir('auth') {
                    sh 'npm install'
                }
            }
        }

        stage('Run tests') {
            steps {
                sh 'npm test || echo "Tests skipped"' // opcional si aún no tienes tests
            }
        }

        stage('SonarQube Analysis') {
            def scannerHome = tool 'SonarScanner'
            environment {
                SONAR_AUTH_TOKEN = credentials('sonarqube-token')
                SONAR_HOST_URL = 'http://sonarqube:9000'
            }
            withSonarQubeEnv() {
                sh "${scannerHome}/bin/sonar-scanner"
            }

            steps {
                echo "==========================================="
                echo "🔍 Analizando calidad de código con SonarQube..."
                echo "==========================================="
                dir('auth') {
                        sh """
                        echo $SONAR_HOST_URL

                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=auth-service \
                        -Dsonar.projectName=auth-service \
                        -Dsonar.sources=. \
                        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login=$SONAR_AUTH_TOKEN
                    """
                    }
                ///withSonarQubeEnv('sonarqube') {
               ///     
               ///}
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}