pipeline {
    agent any

    tools {
        nodejs "nodeForAuth"
    }

    environment {
        SCANNER_HOME = tool "sonarqube"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                git branch: 'automatizacion-04', url: 'https://github.com/odiador/retos-microservicios.git'
                sh 'cd auth'
                sh 'pwd'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pwd'
                echo "==========================================="
                echo "📦 Instalando dependencias de Node.js..."
                echo "==========================================="
                sh 'node --version'
                sh 'npm --version'
                sh 'npm install'
            }
        }

        stage('Run tests') {
            steps {
                sh 'npm test || echo "Tests skipped"' // opcional si aún no tienes tests
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=auth-service \
                        -Dsonar.projectName=auth-service \
                        -Dsonar.sources=src \
                        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login=$SONAR_AUTH_TOKEN
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}