FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install --production

# Copy application code
COPY . .

# Expose port
EXPOSE 3600

# Start application
CMD ["npm", "start"]
